name: TEstime workflow

on:
  schedule:
    - cron: '0 8 * * *'

jobs:
  daily_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3.3.0

      - name: Run Unit Tests
        run: mvn test
    
    
